import 'package:flutter/material.dart';

class AppColors {
  static const Color primary = Color(0xFF5A85F4);
  static const Color secondary = Color(0xFFFFC857);
  static const Color transparent = Colors.transparent;
  static const Color white = Color(0xffFFFFFF);
  static const Color backgroundColor = Color(0xffF5F5FA);
  static const Color iconApp = Color(0xFF27265F);
  static const Color accentColor = Color(0xFF333333);
  static const Color blackPurple = Color(0xFF1A1D21);
  static const Color textColor = Color(0xFF333333);
  static const Color cursorColor = Color(0xFF333333);
  static const Color red = Color(0xFFFE5F55);
  static const Color greenLight = Color(0xFF06D6A0);
  static const Color glassGreen = Color(0xFF214F5D);
  static const Color green = Color(0xFF2CA02C);
  static const Color gray = Color(0xFF9A9BA0);
  static const Color grayBrown = Color(0xFF7D7D7D);
  static const Color grayBold = Color(0xFF4E4D51);
  static const Color sliver = Color(0xFFE0E0E0);
  static const Color lightGray = Color(0xFFF3F3F4);
  static const Color blue = Color(0xFF1F77B4);
  static const Color blueSky = Color(0xFF01D0FA);
  static const Color black = Color(0xFF000000);
  static const Color blackGreen = Color(0xFF1A2427);
  static const Color lightBlue = Color(0xFF96D7FF);
  static const Color warning = Color(0xFFFD9827);
  static const Color orange = Color(0xFFFD9827);
  static const Color sliverLight = Color(0xFF283A48);
  static const Color sliverHighLight = Color(0xFF678DA9);
  static const Color brow = Color(0xFF232429);
  static const Color browBold = Color(0xFF333333);
  static const Color purpleBlue = Color(0xFF448DFD);
  static const Color purpleBlueBold = Color(0xFF6C63FF);
  static const Color purple = Color(0xFF3E4063);
  static const Color pink = Color(0xFFEB005E);
  static const Color grayBackground = Color(0xFF8C8996);
  static const Color appBg = Color(0xFFE5E5E5);
}
